substitutions:
  _SERVICE: bicycle-calculator

steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --tag
      - asia.gcr.io/$PROJECT_ID/${_SERVICE}:$BUILD_ID
      - .

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - asia.gcr.io/$PROJECT_ID/${_SERVICE}:$BUILD_ID

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE}
      - --image=asia.gcr.io/$PROJECT_ID/${_SERVICE}:$BUILD_ID
      - --region=asia-east1
      - --platform=managed
      - --allow-unauthenticated

images:
  - asia.gcr.io/$PROJECT_ID/${_SERVICE}:$BUILD_ID
