server {
    listen 8080;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location = /pacer {
        return 301 /pacer/;
    }

    location = /predict {
        return 301 /predict/;
    }

    location / {
        try_files $uri $uri/ =404;
    }
}
